### PR TITLE
Port to new, multi-targeting project style, add .net standard build, refresh Travis and AppVeyor builds. 

### PR DESCRIPTION
**Pull request by gdziadkiewicz**
# Changes
* Updated `.gitignore` to GitHub VisualStudio version.
* Removed old project and solutions, replaced them with one, multi-targeting solution.
* Added .NET Standard target.
* Updated Travis and AppVeyor configs.
* Updated NUnit and FsUnit versions (it required small, simple fixes).
* Added some conditional compilation to maintain .net 4.0 support(F# Core version and some API changes).

# TODO
* Add mono and osx build on Travis.
* Update README.md.
* ~Update Nuget package publishing mechanism (it can be moved to the proj file together with all necessary information).~ Done in fa70500
* Turn on Travis and AppVeyor builds for this repo, add the build badges to README.

# Assumptions
* I have assumed that the tests are god way to test the package. They all pass.

Link to AppVeyor build on my fork: https://ci.appveyor.com/project/gdziadkiewicz/foq
Link to Travis build on my fork: https://travis-ci.org/gdziadkiewicz/Foq

### CODE REVIEW

**Comment by gdziadkiewicz** [comment]
@ptrelford , do you like the idea and implementation? If yes then do you find it acceptable and ready to merge in this state? If no then what other, acceptable for you, ways to support .net core do you see?

**Comment by ptrelford** [comment]
thanks! Looks great, sorry for the delayed response, I'm not getting notifications from github, please ping me in to action via twitter @ptrelford

**Comment by ptrelford** [comment]
Oops looks like there's some conflicts....

**Comment by whitebear-gh** [comment]
Hi guys, what about this one? I would like to use foq in my core project.

**Comment by gdziadkiewicz** [comment]
Hi, I will resolve the conflicts today.

**Comment by saul** [comment]
Just released Foq 1.8.0 which has these changes. Thanks @gdziadkiewicz

**Pull request merged**
